"use client";
import { useState, type FormEvent } from "react";
import type { Explanation, IncomeLine } from "@/lib/data/types";
import { money, pct } from "./workspace";
export default function CommentaryCard({ row, line, busy, action }: { row: Explanation; line: IncomeLine; busy: boolean; action: (operation:string,values:Record<string,unknown>)=>Promise<unknown> }) {
 const [draft,setDraft]=useState(row.explanation || ""),[context,setContext]=useState("");
 async function save(e:FormEvent<HTMLFormElement>) { e.preventDefault(); await write("draft"); }
 async function write(status:string) { await action("explanation.save",{id:row.id,explanation:draft,review_status:status,expected_amount:row.variance_amount,expected_percent:row.variance_pct,expected_text:row.explanation}).catch(()=>{}); }
 return <article className="commentary-card"><div className="commentary-card-head"><div><h3>{line.account_name}</h3><p>{({budget:"vs monthly budget",prior_month:"vs prior month",prior_ytd:"vs prior year YTD"})[row.variance_type]} · <strong>{money(row.variance_amount)}</strong> · {pct(row.variance_pct)}</p></div><span className={`badge ${row.review_status}`}>{row.review_status}</span></div><form onSubmit={save}><label>Variance explanation<textarea aria-label={`Explanation for ${line.account_name} ${row.variance_type}`} value={draft} onChange={e=>setDraft(e.target.value)} required maxLength={10000} /></label><div className="provenance"><span>{row.explanation_source==="ai" ? `AI draft · Confidence ${pct(row.confidence == null ? null : Number(row.confidence)*100)}` : row.explanation_source==="human" ? "Written or edited by finance" : "No explanation yet"}</span>{row.review_status==="approved" && <span>Approved · AI edits locked</span>}{draft !== (row.explanation || "") && <span className="unsaved">Unsaved edits</span>}</div><div className="button-row"><button type="submit" className="secondary" disabled={busy || !draft.trim() || (row.review_status === "approved" && draft === row.explanation)}>Save draft</button><button type="button" disabled={busy || !draft.trim() || (row.review_status==="approved" && draft===row.explanation)} onClick={()=>write("approved")}>Approve explanation</button></div></form>{row.review_status!=="approved" && <details><summary>Draft with AI</summary><label>Known facts or context (optional)<textarea aria-label={`Finance context for ${line.account_name} ${row.variance_type}`} placeholder="Add verified causes, tenant changes, or one-off costs. Without context, AI describes the figures and suggests what to investigate." value={context} onChange={e=>setContext(e.target.value)} maxLength={10000} /></label><button className="secondary" disabled={busy || draft !== (row.explanation || "")} onClick={()=>action("ai.draft",{id:row.id,context}).catch(()=>{})}>{busy ? "Drafting…" : "Draft explanation"}</button><small>AI drafts require your review. Save edits before requesting a new AI draft.</small></details>}</article>;
}

