"use client";
import { useEffect, useState, useCallback, type ReactNode, type FormEvent } from "react";
import Link from "next/link";
import type { Snapshot, Property, IncomeLine, BalanceLine } from "@/lib/data/types";
import { computeVariances, variance, kpis } from "@/lib/utils/variance";
export const money = (n: number | null | undefined) => new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 }).format(Number(n || 0));
export const pct = (n: number | null | undefined) => n == null ? "N/A" : `${Number(n).toFixed(1)}%`;
type Field = { name: string; label: string; type?: string; options?: string[]; min?: number; max?: number; required?: boolean };
type Editor = { title: string; operation: string; fields: Field[]; initial: Record<string, unknown>; extra?: Record<string, unknown> };
const propertyFields: Field[] = [{ name: "name", label: "Property name" }, { name: "property_type", label: "Type", options: ["office", "retail", "industrial", "residential", "mixed"] }, { name: "location", label: "Location", required: false }, { name: "acquisition_date", label: "Acquisition date", type: "date", required: false }, { name: "purchase_price", label: "Purchase price (AUD)", type: "number", min: 0 }];
const periodFields: Field[] = [{ name: "period_year", label: "Year", type: "number", min: 1900, max: 2200 }, { name: "period_month", label: "Month", type: "number", min: 1, max: 12 }, { name: "status", label: "Status", options: ["open", "closed"] }];
const lineFields = (balance: boolean): Field[] => [{ name: "account_name", label: "Account name" }, { name: "account_category", label: "Category", options: balance ? ["asset", "liability", "equity"] : ["revenue", "opex", "capex", "other"] }, ... (balance ? ["actual", "prior_period"] : ["actual", "budget", "prior_month", "prior_ytd", "ytd_actual"]).map(name => ({ name, label: ({ actual: "Monthly actual", budget: "Monthly budget", prior_month: "Prior month actual", prior_ytd: "Prior year YTD", ytd_actual: "Current YTD actual", prior_period: "Prior period" } as Record<string, string>)[name], type: "number" }))];
export function Panel({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <section className="panel"><div className="panel-head"><h2>{title}</h2>{action}</div>{children}</section>; }
export function Empty({ children }: { children: ReactNode }) { return <div className="empty">{children}</div>; }
export default function Workspace({ section = "dashboard" }: { section?: string }) {
  const [data, setData] = useState<Snapshot | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [propertyId, setPropertyId] = useState(""), [periodId, setPeriodId] = useState(""), [tab, setTab] = useState("income"), [editor, setEditor] = useState<Editor | null>(null), [menu, setMenu] = useState(false);
  const load = useCallback(async () => {
    const response = await fetch("/api/workspace", { cache: "no-store" });
    const body = await response.json();
    if (!response.ok) throw new Error(body.error);
    setData(body);
    const query = new URLSearchParams(window.location.search);
    setPropertyId(current => body.properties.some((p: Property) => p.id === current) ? current : body.properties.find((p: Property) => p.id === query.get("property"))?.id || body.properties[0]?.id || "");
    setPeriodId(current => body.periods.some((p: { id: string }) => p.id === current) ? current : body.periods.find((p: { id: string }) => p.id === query.get("period"))?.id || body.periods[0]?.id || "");
  }, []);
  useEffect(() => { load().catch(e => setError(e.message)); }, [load]);
  useEffect(() => { if (propertyId && periodId) window.history.replaceState(null, "", `${window.location.pathname}?property=${propertyId}&period=${periodId}`); }, [propertyId, periodId]);
  async function action(operation: string, values: Record<string, unknown>) {
    setBusy(true); setError(""); setNotice("");
    try {
      const response = await fetch(operation === "upload.delete" ? "/api/uploads" : "/api/workspace", { method: operation === "upload.delete" ? "DELETE" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(operation === "upload.delete" ? values : { operation, values }) });
      const body = await response.json(); if (!response.ok) throw new Error(body.error);
      await load(); setEditor(null); setNotice(body.warning || "Saved to the database.");
      if (operation === "property.save" && !values.id) setPropertyId(body.result.id);
      if (operation === "period.save" && !values.id) setPeriodId(body.result.id);
      return body.result;
    } catch (e) { setError(e instanceof Error ? e.message : "Unable to save."); throw e; } finally { setBusy(false); }
  }
  async function uploadReport(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = e.currentTarget, payload = new FormData(form); payload.set("property_id",propertyId); payload.set("period_id",periodId);
    setBusy(true); setError(""); setNotice("");
    try { const response = await fetch("/api/uploads", { method: "POST", body: payload }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); form.reset(); setNotice("Report uploaded and stored for this property and period."); } catch(error) { setError(error instanceof Error ? error.message : "Upload failed."); } finally { setBusy(false); }
  }
  function pasteLines() { setEditor({ title: "Paste income statement rows", operation: "income.paste", fields: [{ name: "rows", label: "7 columns: account_name, category, actual, budget, prior_month, prior_ytd, ytd_actual. Paste tab-separated rows from Excel, or CSV (optional header).", type: "textarea" }], initial: {}, extra: { property_id: propertyId, period_id:periodId } }); }
  function editThresholds() { setEditor({ title: "Materiality thresholds", operation: "settings.save", fields: [{ name: "amount_threshold", label: "Absolute amount greater than (AUD)", type: "number", min: 0 }, { name: "percent_threshold", label: "Absolute percentage greater than (%)", type: "number", min: 0 }], initial: { amount_threshold: thresholds.amount, percent_threshold:thresholds.percent }, extra: { property_id:propertyId,period_id:periodId } }); }
  function editProperty(p?: Property) { setEditor({ title: p ? "Edit property" : "Add property", operation: "property.save", fields: propertyFields, initial: p ? { ...p } : { property_type: "office", purchase_price: 0 } }); }
  function editPeriod() { const now = new Date(); setEditor({ title: "Add reporting period", operation: "period.save", fields: periodFields, initial: { period_year: now.getFullYear(), period_month: now.getMonth() + 1, status: "open" } }); }
  function editLine(balance: boolean, line?: IncomeLine | BalanceLine) { setEditor({ title: `${line ? "Edit" : "Add"} ${balance ? "balance sheet" : "income statement"} line`, operation: balance ? "balance.save" : "income.save", fields: lineFields(balance), initial: line ? { ...line } : { account_category: balance ? "asset" : "revenue", actual: 0, budget: 0, prior_month: 0, prior_ytd: 0, ytd_actual: 0, prior_period: 0 }, extra: { property_id: propertyId, period_id: periodId } }); }
  function confirmDelete(operation: string, id: string, label: string) { setEditor({ title: `Delete ${label}?`, operation, fields: [{ name: "reason", label: "Reason for deletion" }], initial: {}, extra: { id, confirm: true } }); }
  const property = data?.properties.find(p => p.id === propertyId), period = data?.periods.find(p => p.id === periodId);
  const income = data?.income.filter(l => l.property_id === propertyId && l.period_id === periodId) || [], balance = data?.balance.filter(l => l.property_id === propertyId && l.period_id === periodId) || [];
  const selectedSettings = data?.settings.find(s => s.property_id === propertyId && s.period_id === periodId);
  const thresholds = { amount: Number(selectedSettings?.amount_threshold ?? 5000), percent: Number(selectedSettings?.percent_threshold ?? 10) };
  const flagged = income.flatMap(l => computeVariances(l, thresholds.amount, thresholds.percent).filter(v => v.material).map(v => ({ ...v, line: l }))).sort((a, b) => Math.abs(b.amount) - Math.abs(a.amount));
  const link = (path: string, p = propertyId) => `${path}?property=${p}&period=${periodId}`;
  return <div className="app-shell">
    <aside className={`sidebar ${menu ? "visible" : ""}`}><Link href={link("/")} className="brand"><span className="brand-icon">M</span><div>Metric<span>PROPERTY REPORTING</span></div></Link><span className="nav-label">WORKSPACE</span><nav>{[["dashboard", "Dashboard", "◈"], ["properties", "Properties", "▦"], ["reports", "Financial reports", "▤"], ["commentary", "Commentary", "◌"]].map(([key, label, icon]) => <Link key={key} href={link(`/${key}`)} className={section === key ? "active" : ""}><span>{icon}</span>{label}{key === "commentary" && flagged.length > 0 && <small>{flagged.length}</small>}</Link>)}</nav><div className="nav-label">YOUR PROPERTIES</div><div className="property-nav">{data?.properties.map(p => <button key={p.id} className={p.id === propertyId ? "selected" : ""} onClick={() => { setPropertyId(p.id); setMenu(false); }}><span className="dot" />{p.name}</button>)}</div><button className="sidebar-add" onClick={() => editProperty()}>+ Add property</button><div className="sidebar-bottom"><span className="avatar">FT</span><div>Finance workspace<span>Shared demo · AUD</span></div></div></aside>
    <main className="main"><header className="topbar"><button className="mobile-menu secondary" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">☰</button><span>Workspace <span className="muted">/</span> {({ dashboard: "Overview", properties: "Properties", reports: "Financial reports", commentary: "Commentary" } as Record<string,string>)[section]}</span><div className="top-actions"><label className="sr-only" htmlFor="period">Reporting period</label><select id="period" value={periodId} onChange={e => setPeriodId(e.target.value)}>{data?.periods.map(p => <option key={p.id} value={p.id}>{p.label} · {p.status}</option>)}</select><button className="secondary" onClick={editPeriod}>+ Period</button></div></header>
      <div className="content"><div className="page-heading"><div><div className="eyebrow">MONTHLY MANAGEMENT REPORTING</div><h1>{({ dashboard: "Portfolio overview", properties: "Your properties", reports: "Financial reports", commentary: "Variance commentary" } as Record<string,string>)[section]}</h1><p>{section === "dashboard" ? "Performance, material movements, and the story behind the numbers." : section === "properties" ? "Manage the assets behind your monthly reporting." : `${property?.name || "Select a property"} · ${period?.label || "Select a period"}`}</p></div>{section === "properties" ? <button onClick={() => editProperty()}>+ Add property</button> : <div className="selection"><label htmlFor="property" className="sr-only">Property</label><select id="property" value={propertyId} onChange={e => setPropertyId(e.target.value)}>{data?.properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div>}</div>
      {error && <div className="alert error" role="alert">{error}{!data && <button className="secondary" onClick={() => { setError(""); load().catch(e => setError(e.message)); }}>Retry</button>}</div>}{notice && <div className="alert success" role="status">{notice}</div>}
      {!data && !error && <div className="loading" aria-busy="true">Loading your reporting workspace…<div className="skeleton" /><div className="skeleton" /></div>}
      {data && section === "properties" && <div className="property-grid">{data.properties.length === 0 && <Empty>No properties yet. Create your first property to get started.</Empty>}{data.properties.map(p => <Panel key={p.id} title={p.name}><div className="property-type">{p.property_type} <span className="muted">· {p.location || "Location not set"}</span></div><div className="property-value"><small>ACQUISITION VALUE</small><strong>{money(p.purchase_price)}</strong></div><p className="muted">Acquired {p.acquisition_date || "—"}</p><div className="button-row"><Link className="button" href={link("/reports", p.id)}>Open reports →</Link><button className="secondary" onClick={() => editProperty(p)}>Edit</button><button className="danger" onClick={() => confirmDelete("property.delete", p.id, `${p.name} and all its reporting data`)}>Delete</button></div></Panel>)}</div>}
      {data && section !== "properties" && (!property || !period) && <Empty>Create a property and reporting period to start reporting.</Empty>}
      {data && section === "reports" && property && period && <>
        <div className="tabs"><button className={tab === "income" ? "active" : ""} onClick={() => setTab("income")}>Income statement</button><button className={tab === "balance" ? "active" : ""} onClick={() => setTab("balance")}>Balance sheet</button><span>{period.status === "closed" ? "Closed period" : "Open for entry"}</span><button className="secondary" disabled={busy} onClick={() => action("period.save", { ...period, status: period.status === "closed" ? "open" : "closed" }).catch(() => {})}>{period.status === "closed" ? "Reopen period" : "Close period"}</button></div>
        <Panel title={tab === "income" ? "Income statement" : "Balance sheet"} action={<div className="button-row">{tab === "income" && <button className="secondary" disabled={busy || period.status === "closed"} onClick={pasteLines}>Paste rows</button>}<button disabled={busy || period.status === "closed"} onClick={() => editLine(tab === "balance")}>+ Add line</button></div>}>
        {tab === "income" ? income.length === 0 ? <Empty>No income statement data for this period. Add your first line item.</Empty> : <div className="table-wrap"><table><thead><tr><th>Account</th><th>Actual</th><th>Budget</th><th>vs budget</th><th>Prior month</th><th>vs prior month</th><th>Current YTD</th><th>Prior year YTD</th><th>vs prior YTD</th><th>Actions</th></tr></thead><tbody>{income.map(l => { const vs = computeVariances(l, thresholds.amount, thresholds.percent); return <tr key={l.id}><td><strong>{l.account_name}</strong><small>{l.account_category}</small></td><td>{money(l.actual)}</td><td>{money(l.budget)}</td><td className={vs[0].material ? "material" : ""}>{money(vs[0].amount)}<small>{pct(vs[0].percent)}{vs[0].material && " · Material"}</small></td><td>{money(l.prior_month)}</td><td className={vs[1].material ? "material" : ""}>{money(vs[1].amount)}<small>{pct(vs[1].percent)}{vs[1].material && " · Material"}</small></td><td>{money(l.ytd_actual)}</td><td>{money(l.prior_ytd)}</td><td className={vs[2].material ? "material" : ""}>{money(vs[2].amount)}<small>{pct(vs[2].percent)}{vs[2].material && " · Material"}</small></td><td><div className="button-row"><button className="text-button" disabled={period.status === "closed"} onClick={() => editLine(false, l)}>Edit</button><button className="text-button danger" disabled={period.status === "closed"} onClick={() => confirmDelete("income.delete", l.id, l.account_name)}>Delete</button></div></td></tr>; })}</tbody></table></div> : balance.length === 0 ? <Empty>No balance sheet data for this period. Add your first balance sheet line.</Empty> : <div className="table-wrap"><table><thead><tr><th>Account</th><th>Actual</th><th>Prior period</th><th>Movement</th><th>Movement %</th><th>Actions</th></tr></thead><tbody>{balance.map(l => { const v = variance(Number(l.actual), Number(l.prior_period), thresholds.amount, thresholds.percent); return <tr key={l.id}><td><strong>{l.account_name}</strong><small>{l.account_category}</small></td><td>{money(l.actual)}</td><td>{money(l.prior_period)}</td><td className={v.material ? "material" : ""}>{money(v.amount)}{v.material && <small>Material movement</small>}</td><td>{pct(v.percent)}</td><td><div className="button-row"><button className="text-button" disabled={period.status === "closed"} onClick={() => editLine(true, l)}>Edit</button><button className="text-button danger" disabled={period.status === "closed"} onClick={() => confirmDelete("balance.delete", l.id, l.account_name)}>Delete</button></div></td></tr>; })}</tbody></table></div>}
        <div className="panel-footer">Material when absolute movement exceeds {money(thresholds.amount)} AND {thresholds.percent}%. N/A indicates a zero comparison base. <button className="text-button" disabled={busy || period.status === "closed"} onClick={editThresholds}>Configure thresholds</button></div></Panel><Panel title="Top material movements" action={<Link href={link("/commentary")} className="text-button">Review commentary →</Link>}>{flagged.length === 0 ? <Empty>All variances within threshold. No commentary needed.</Empty> : flagged.slice(0, 5).map(v => <div className="movement" key={`${v.line.id}-${v.type}`}><div><strong>{v.line.account_name}</strong><small>{v.type.replaceAll("_", " ")}</small></div><strong className="material">{money(v.amount)} <small>{pct(v.percent)}</small></strong></div>)}</Panel>
<Panel title="Monthly source reports"><div className="upload-area"><p>Store the source report, then enter or paste its financial lines above.</p><form onSubmit={uploadReport} className="upload-form"><label htmlFor="report-file" className="sr-only">Source report file</label><input id="report-file" name="file" type="file" accept=".pdf,.xlsx,.xls,.csv" required disabled={busy || period.status === "closed"} /><button disabled={busy || period.status === "closed"}>{busy ? "Uploading…" : "Upload report"}</button></form><small>PDF, Excel, or CSV · up to 4 MB · Stored privately</small></div>{data.uploads.filter(u => u.property_id === propertyId && u.period_id === periodId).map(u => <div key={u.id} className="movement"><div><strong>{u.file_name}</strong><small>{new Date(u.created_at).toLocaleDateString("en-AU")} · {u.uploaded_by}</small></div><div className="button-row"><a className="text-button" href={`/api/uploads?id=${u.id}`} target="_blank" rel="noreferrer">Download</a><button className="text-button danger" disabled={busy || period.status === "closed"} onClick={() => confirmDelete("upload.delete",u.id,u.file_name)}>Delete</button></div></div>)}</Panel>
      </>}
      {data && section === "dashboard" && <><div className="kpi-grid">{(() => { const lines = data.income.filter(l => l.period_id === periodId), metrics = kpis(lines, data.properties.reduce((s, p) => s + Number(p.purchase_price || 0), 0)); return [["Portfolio revenue", money(metrics.revenue), "Monthly actual revenue"], ["Operating profit", money(metrics.profit), "Revenue less operating expenses"], ["Operating margin", pct(metrics.margin), "Profit / monthly revenue"], ["YTD revenue yield", pct(metrics.yield), "YTD revenue / acquisition cost"]].map(([label, value, note]) => <div className="kpi" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>); })()}</div><Panel title="Property performance" action={<span className="badge">{period?.label || "No period"}</span>}>{data.properties.length === 0 ? <Empty>No properties yet. Create your first property to get started.</Empty> : <div className="table-wrap"><table><thead><tr><th>Property</th><th>Revenue</th><th>vs budget</th><th>Margin</th><th>YTD yield</th><th>Report</th></tr></thead><tbody>{data.properties.map(p => { const lines = data.income.filter(l => l.property_id === p.id && l.period_id === periodId), k = kpis(lines, Number(p.purchase_price)); return <tr key={p.id}><td><strong>{p.name}</strong><small>{p.location} · {p.property_type}</small></td><td>{lines.length ? money(k.revenue) : "No data"}</td><td>{lines.length ? money(k.revenueVariance) : "—"}</td><td>{pct(k.margin)}</td><td>{lines.length ? pct(k.yield) : "—"}</td><td><Link className="text-button" href={link("/reports", p.id)}>View report →</Link></td></tr>; })}</tbody></table></div>}</Panel><Panel title="Approved management commentary">{data.explanations.filter(e => e.period_id === periodId && e.review_status === "approved").length === 0 ? <Empty>No approved commentary for this period. Review material variances to add the management narrative.</Empty> : data.explanations.filter(e => e.period_id === periodId && e.review_status === "approved").map(e => <div className="comment" key={e.id}><div><strong>{data.properties.find(p => p.id === e.property_id)?.name}</strong><span className="badge approved">Approved</span></div><p>{e.explanation}</p></div>)}</Panel></>}
      {data && section === "commentary" && <Panel title="Material variances">{flagged.length === 0 ? <Empty>All variances within threshold. No commentary needed.</Empty> : flagged.map(v => <div className="movement" key={`${v.line.id}-${v.type}`}><div><strong>{v.line.account_name}</strong><small>{v.type.replaceAll("_", " ")}</small></div><strong className="material">{money(v.amount)} · {pct(v.percent)}</strong></div>)}</Panel>}
      <footer>Metric · Management reporting <span>Amounts in AUD · Financial figures entered by your team</span></footer></div>
    </main>
    {editor && <EditorForm editor={editor} busy={busy} error={error} close={() => setEditor(null)} save={action} />}
  </div>;
}
function EditorForm({ editor, busy, error, close, save }: { editor: Editor; busy: boolean; error: string; close: () => void; save: (operation: string, values: Record<string, unknown>) => Promise<unknown> }) {
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const values = Object.fromEntries(new FormData(e.currentTarget)); await save(editor.operation, { ...editor.initial, ...values, ...editor.extra }).catch(() => {}); }
  return <div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="editor-title" className="modal"><div className="panel-head"><h2 id="editor-title">{editor.title}</h2><button className="text-button" disabled={busy} aria-label="Close form" onClick={close}>✕</button></div><form onSubmit={submit}>{editor.operation.endsWith(".delete") && <div className="alert error">This permanently removes the record and its related data.</div>}<div className="form-grid">{editor.fields.map((f, index) => <label key={f.name}>{f.label}{f.options ? <select name={f.name} defaultValue={String(editor.initial[f.name] ?? f.options[0])} required>{f.options.map(o => <option key={o}>{o}</option>)}</select> : f.type === "textarea" ? <textarea autoFocus={index === 0} name={f.name} rows={9} required defaultValue={String(editor.initial[f.name] ?? "")} /> : <input autoFocus={index === 0} name={f.name} type={f.type || "text"} step={f.type === "number" ? "any" : undefined} min={f.min} max={f.max} defaultValue={String(editor.initial[f.name] ?? "")} required={f.required !== false} />}</label>)}</div>{error && <p role="alert" className="error-text">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button><button disabled={busy} className={editor.operation.endsWith(".delete") ? "danger solid" : ""}>{busy ? "Saving…" : editor.operation.endsWith(".delete") ? "Confirm deletion" : "Save changes"}</button></div></form></section></div>;
}

