import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const database = new PGlite();
const one = async (sql, params = []) => (await database.query(sql, params)).rows[0];
test('database workflow: seed, insert, thresholds, review, staleness, closed period, audited deletion', async () => {
 await database.exec(`create schema auth; create function auth.uid() returns uuid language sql as 'select null::uuid'; create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]); create table storage.objects(id uuid,bucket_id text); alter table storage.objects enable row level security;`);
 for (const name of ['0001_init.sql','0002_reporting_workflow.sql','0003_commentary_review.sql']) await database.exec(await readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));
 const property='a0000000-0000-4000-8000-000000000001', period='b0000000-0000-4000-8000-000000000001';
 const line=await one(`insert into income_statement_lines(property_id,period_id,account_name,account_category,actual,budget,prior_month,prior_ytd,ytd_actual) values($1,$2,'Integration rent','revenue',450000,400000,380000,900000,1350000) returning *`,[property,period]);
 const explanations=(await database.query('select * from variance_explanations where income_line_id=$1',[line.id])).rows;
 assert.equal(explanations.length,3); assert.equal(explanations.filter(e=>e.is_material).length,3);
 const row=explanations.find(e=>e.variance_type==='budget');
 await database.query(`select save_variance_explanation($1,'Verified new leases','draft','ai',0.8,$2,$3,null)`,[row.id,row.variance_amount,row.variance_pct]);
 await database.query(`select save_variance_explanation($1,'Verified new leases','approved','ai',0.8,$2,$3,'Verified new leases')`,[row.id,row.variance_amount,row.variance_pct]);
 await assert.rejects(database.query(`select save_variance_explanation($1,'Overwrite','draft','ai',0.8,$2,$3,'Verified new leases')`,[row.id,row.variance_amount,row.variance_pct]),/locked/);
 await database.query('update income_statement_lines set actual=460000 where id=$1',[line.id]);
 const changed=await one('select * from variance_explanations where id=$1',[row.id]);
 assert.equal(changed.review_status,'draft'); assert.equal(Number(changed.variance_amount),60000);
 await assert.rejects(database.query(`select save_variance_explanation($1,'Old figures','approved','human',null,$2,$3,'Verified new leases')`,[row.id,row.variance_amount,row.variance_pct]),/changed/);
 await database.query(`insert into report_settings(property_id,period_id,amount_threshold,percent_threshold) values($1,$2,70000,10)`,[property,period]);
 assert.equal((await one('select is_material from variance_explanations where id=$1',[row.id])).is_material,false);
 await database.query(`update reporting_periods set status='closed' where id=$1`,[period]);
 await assert.rejects(database.query('update income_statement_lines set actual=1 where id=$1',[line.id]),/closed/);
 await assert.rejects(database.query(`insert into report_uploads(property_id,period_id,file_name) values($1,$2,'bad.csv')`,[property,period]),/closed/);
 await database.query(`update reporting_periods set status='open' where id=$1`,[period]);
 await database.query(`select delete_reporting_record('income_statement_lines',$1,'Integration cleanup')`,[line.id]);
 assert.equal((await one('select count(*)::int as n from variance_explanations where income_line_id=$1',[line.id])).n,0);
 const audit=await one(`select * from audit_logs where target_id=$1 and action_name='delete_record'`,[line.id]);
 assert.equal(audit.details_json.reason,'Integration cleanup');
 assert.ok((await one(`select count(*)::int as n from audit_logs where action_name='approve_explanation'`)).n>0);
 await database.close();
});
